# Generated by Django 5.1.3 on 2025-01-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_alter_contracts_business_entities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='business_entity_type',
            field=models.CharField(blank=True, choices=[('TOV', 'ТОВ'), ('FOP', 'ФОП')], default='FOP', max_length=3, null=True),
        ),
    ]
