# Generated by Django 5.1.3 on 2025-01-09 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_templates_business_entity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='contracts',
            name='path',
            field=models.FileField(blank=True, max_length=256, null=True, upload_to='uploads/'),
        ),
    ]
