# Generated by Django 5.1.3 on 2025-01-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_contracts_name_contracts_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templates',
            name='type',
        ),
        migrations.AlterField(
            model_name='templates',
            name='path',
            field=models.FileField(blank=True, null=True, upload_to='uploads/templates/'),
        ),
    ]
