# Generated by Django 5.1.3 on 2025-01-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_remove_templates_type_alter_templates_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contracts',
            name='name',
        ),
        migrations.RemoveField(
            model_name='contracts',
            name='path',
        ),
        migrations.AddField(
            model_name='templates',
            name='font',
            field=models.CharField(blank=True, choices=[('Arial', 'Arial'), ('Times New Roman', 'Times New Roman')], default='Times New Roman', null=True),
        ),
    ]
