# Generated by Django 5.1.3 on 2025-01-16 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_remove_contracts_name_remove_contracts_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templates',
            name='font',
        ),
    ]
