# Generated by Django 5.1.3 on 2025-01-16 23:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_remove_templates_font'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
