# Generated by Django 5.1.3 on 2025-01-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_alter_contracts_end_date_alter_contracts_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='template_type',
            field=models.CharField(blank=True, choices=[('ROYAL', 'РОЯЛ'), ('ROLAND', 'РОЛАНД')], default='ROYAL', null=True),
        ),
    ]
