# Generated by Django 5.1.3 on 2025-01-29 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_entities', '0001_initial'),
        ('contracts', '0009_templates_template_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='business_entities',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business_entities.businessentities'),
        ),
    ]
