# Generated by Django 5.1.3 on 2024-12-29 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessEntities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_entity', models.CharField(choices=[('TOV', 'ТОВ'), ('FOP', 'ФОП')], default='FOP', max_length=3)),
                ('edrpou', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Code EDRPOU')),
                ('company_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Company Name')),
                ('director_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Director Name')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Phone')),
                ('iban', models.CharField(blank=True, max_length=200, null=True, verbose_name='IBAN')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_entities', to='banks.bank')),
            ],
        ),
    ]
