# Generated by Django 5.1.3 on 2024-12-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_entities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessentities',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='businessentities',
            name='short_name',
        ),
        migrations.AddField(
            model_name='businessentities',
            name='company_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='businessentities',
            name='director_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Director Name'),
        ),
    ]
