# Generated by Django 5.1.3 on 2025-02-06 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_entities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessentities',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='businessentities',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='businessentities',
            name='director_name',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Director Name'),
        ),
        migrations.AlterField(
            model_name='businessentities',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='businessentities',
            name='iban',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='IBAN'),
        ),
        migrations.AlterField(
            model_name='businessentities',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Phone'),
        ),
    ]
