repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types:
          - python
        args: [ -t py312 ]
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types:
          - python
        args:
          - --ignore=I101,I100,W503
      - id: isort
        name: isort
        entry: isort
        language: system
        types:
          - python
        args:
          - --profile=black
          - --line-length=88
