# Generated by Django 5.1.3 on 2025-01-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='vin_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
