# Generated by Django 5.1.3 on 2024-12-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='euro',
            field=models.CharField(blank=True, choices=[('Euro 1', 'ЄВРО 1'), ('Euro 2', 'ЄВРО 2'), ('Euro 3', 'ЄВРО 3'), ('Euro 4', 'ЄВРО 4'), ('Euro 5', 'ЄВРО 5'), ('Euro 6', 'ЄВРО 6'), ('Euro 7', 'ЄВРО 7')], default='Euro 1', null=True),
        ),
    ]
