# Generated by Django 5.1.3 on 2025-02-06 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehicles_vin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclelicences',
            name='licence_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiclelicences',
            name='serial',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='engine_capacity',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='laden_weight',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='number_of_seats',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='unladen_weight',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('Passenger Car', 'Легковий автомобіль'), ('Truck', 'Вантажний автомобіль'), ('Bus', 'Автобус')], default=''),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='vin_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='year',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
