# Generated by Django 5.1.3 on 2024-12-11 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_alter_vehicles_euro_alter_vehicles_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicles',
            old_name='type',
            new_name='vehicle_type',
        ),
    ]
