# Generated by Django 5.1.3 on 2024-12-12 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_rename_type_vehicles_vehicle_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclelicences',
            old_name='number',
            new_name='licence_number',
        ),
    ]
