# Generated by Django 5.1.3 on 2025-02-06 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='mfo',
            field=models.CharField(blank=True, default='', verbose_name='MFO'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Bank Name'),
        ),
    ]
